title: My personal blog - HeiKay
email: 815347984@qq.com
description: > 
permalink: ':title/'
baseurl: "" 
url: "https://heikay.github.io/"

# Author settings
author: HeiKay
author-pic: adam-face.jpg
about-author: 下手糞の上級者への道のりは己が下手さを知りて一歩目

# Contact links
email: 815347984@qq.com
github: HeiKay

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
